@echo off
echo Adding files to git...
git add .
echo Committing changes...
git commit -m "feat: add rescue resource optimizer, event orchestrator, sensor anomaly detection, response KPI dashboard"
echo Pushing to GitHub main branch...
git push origin main
echo Done! GitHub push complete.
