@echo off
echo Adding files to git...
git add .
echo Committing changes...
git commit -m "fix: lock CORS origins, bake VITE_API_BASE_URL into vercel.json for Vercel-Render connection"
echo Pushing to GitHub main branch...
git push origin main
echo Done! GitHub push complete.
