@echo off
echo Adding files to git...
git add .
echo Committing changes...
git commit -m "feat: complete rebuild and push JWT auth, Officer portal, Gemini Vision, shelters, and PDF export"
echo Pushing to GitHub main branch...
git push origin main
echo Done! GitHub push complete.
